[package]
name = "freeport"
version = "0.2.0"
edition = "2021"

[[bin]]
name = "freeport"
path = "src/main.rs"

[build-dependencies]
slint-build = "1"

[dependencies]
slint = "1"
freeport-core = { path = "../core" }
tokio = { version = "1", features = ["rt-multi-thread"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "stream"] }
rfd = "0.15"
open = "5"
